version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: commenthub_app
    container_name: commenthub_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
        - "8000:8000"
    depends_on:
        - db
    networks:
      - app-network
    command: >
        bash -c "composer install &&
                 php artisan key:generate &&
                 php artisan migrate &&
                 php artisan db:seed &&
                 php-fpm"

  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    image: commenthub_node
    container_name: commenthub_node
    tty: true
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - "3000:3000"
    depends_on:
        - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: commenthub_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: comment_hub
      MYSQL_ROOT_PASSWORD: your_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
